<?xml version="1.0" encoding="utf-8"?><Database Name="MeloManager" Class="MediaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=OLEG-A\SQLEXPRESS;Initial Catalog=MeloManager;Integrated Security=True" SettingsObjectName="Oleg_ivo.MeloManager.MediaObjects.Properties.Settings" SettingsPropertyName="MeloManagerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MediaContainer" Member="MediaContainers">
    <Type Name="MediaContainer" InheritanceCode="MediaContainer" IsInheritanceDefault="true">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsReadOnly="true" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" IsDiscriminator="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="IsRepaired" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="MediaContainer_MediaContainersParentChild" Member="ParentMediaContainers" ThisKey="Id" OtherKey="ChildId" Type="MediaContainersParentChild" />
      <Association Name="MediaContainer_MediaContainersParentChild1" Member="ChildMediaContainers" ThisKey="Id" OtherKey="ParentId" Type="MediaContainersParentChild" />
      <Type Name="Category" InheritanceCode="Category" />
      <Type Name="Playlist" InheritanceCode="Playlist" />
      <Type Name="MediaFile" InheritanceCode="MediaFile" />
    </Type>
  </Table>
  <Table Name="dbo.MediaContainersParentChild" Member="MediaContainersParentChilds">
    <Type Name="MediaContainersParentChild">
      <Column Name="ParentId" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ChildId" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="MediaContainer_MediaContainersParentChild" Member="ChildMediaContainer" ThisKey="ChildId" OtherKey="Id" Type="MediaContainer" IsForeignKey="true" />
      <Association Name="MediaContainer_MediaContainersParentChild1" Member="ParentMediaContainer" ThisKey="ParentId" OtherKey="Id" Type="MediaContainer" IsForeignKey="true" />
    </Type>
  </Table>
</Database>